# 雙埠 + TV 100 (原 1/4)  (port=dual)
name: pixel_dual_tv100
port: dual

epochs: 1000
lr: 0.005
patience: 10

loss:
  total_variation: 100

hfss:
  lr: 0.001
  min_loss: 0.1
  max_epoch: 20000

scheduler:
  on_plateau: linear

surrogate:
  pretrained: patch_dual.pth
  offline_dataset: patch_dual

targets:
  S11: { side: -1.25, center: -12, width: [4, 2, 5, 2, 4], interval: [-1, 1] }
  S21: { side: -20,   center: -3,  width: [3, 0, 11, 0, 3], interval: [-1, 1] }
  S22: { side: -1.25, center: -12, width: [4, 2, 5, 2, 4], interval: [-1, 1] }
