# 單埠 + 孤島抑制 1 (原 10)  (port=single)
name: pixel_single_island1
port: single

epochs: 1000
lr: 0.005
patience: 10

loss:
  island_suppression: 1

sm_train:
  lr: 0.001
  min_loss: 0.1
  max_epoch: 20000

scheduler:
  on_plateau: linear

surrogate:
  pretrained: old_sm.pth
  offline_dataset: patch_single_mirror

targets:
  S11:  { side: 0,   center: -10, width: [5, 0, 7, 0, 5], method: low }
  Gain: { side: -19, center: 4,   width: [5, 0, 7, 0, 5], method: high }
